FROM node:18.20-alpine as build

WORKDIR /app/frontend

COPY package.json .
COPY package-lock.json .

RUN npm install --only=production

COPY . .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build

FROM nginx:1.25-alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html

