version: "3.8"

services:
  backend:
    container_name: tinder-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend:ro
      - backend_dependency:/app/backend/node_modules

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - tinder:/data/db

  frontend:
    container_name: tinder-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
      - front_dependency:/app/frontend/node_modules

    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  tinder:
  front_dependency:
  backend_dependency:
