version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://database/tinder
    env_file:
      - ./backend/.env

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - tinder:/data/db

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  tinder:
