export default [
  {
    images: [
      "https://cdn.vox-cdn.com/thumbor/RX04uAR-GhRdN9-en6PmkSj69iU=/0x0:6080x2546/1200x800/filters:focal(2406x699:3378x1671)/cdn.vox-cdn.com/uploads/chorus_image/image/65753797/elsainfall.0.jpg",
      "https://vignette.wikia.nocookie.net/disney/images/9/95/Profile_-_Elsa.jpeg/revision/latest?cb=20200319054311",
    ],
    name: "Elsa",
    age: 26,
    gender: "Female",
    location: "1 mile away",
    bio: "Ice Queen, literally. Ghost me and I'll find you & freeze you. Just ask my sister.",
    id: 1,
    university: "Arendelle University of Ice and Magic",
    interests: ["Hiking", "Ski", "Learning", "Drawing", "Dance", "Painting"],
  },
  {
    images: [
      "https://media1.popsugar-assets.com/files/thumbor/8AH2numkygyXyu3DWTlrb_EwSuo/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2020/02/19/863/n/3019466/48974ba25e4d8fe6328504.89366186_MCDPRIN_EC07/i/Gemini-May-21-June-20-Tiana.jpg",
      "https://i.pinimg.com/originals/16/5e/e3/165ee335555aaa283db4598f3228762d.gif",
    ],
    name: "Tiana",
    gender: "Female",
    age: 28,
    location: "15 miles away",
    bio: "Entrepreneur. NOLA girl. Firm believer in 'You have to kiss a few frogs to find your Prince Charming'.",
    id: 2,
    university: "Culinary Institute of New Orleans",
    interests: ["Cooking", "Swamp exploration", "Community development"],
  },
  {
    images: [
      "https://compote.slate.com/images/06921e37-f1ab-4396-bdbd-332ee336aea8.jpeg?crop=1560%2C1040%2Cx0%2Cy0&width=1920",
    ],
    name: "Gaston",
    gender: "Male",
    age: 32,
    location: "9 miles away",
    bio: "Here for a good time, not a long time. Eats 5 dozen eggs so I'm roughly the size of a barge.",
    id: 3,
    university: "Arendelle School of Charm and Bravery",
    interests: ["Weightlifting", "Hunting", "Poetry"],
  },
  {
    images: [
      "https://i.pinimg.com/originals/9b/1f/7f/9b1f7fb26329f0fb1bf6cd9a65063f4f.jpg",
      "https://i.pinimg.com/originals/04/f9/35/04f93570abf5044ff3804782a9e2119d.jpg",
    ],
    name: "Flynn",
    gender: "Female",
    age: 25,
    location: "3 miles away",
    bio: "YOLO Enthusiast. Former thief, so I'll steal your heart 😉",
    id: 4,
    university: "School of Adventure and Reformation",
    interests: ["Archery", "Exploring", "Climbing"],
  },
  {
    images: [
      "https://pbs.twimg.com/media/C8HShn0VwAArWJz.jpg",
      "https://i.pinimg.com/736x/95/ee/91/95ee91b6d78ef79a317ab9482e135458.jpg",
    ],
    name: "Shang",
    gender: "Female",
    age: 27,
    location: "2 miles away",
    bio: "Let's get down to business: Ex-military, defeated the Huns, mysterious as the dark side of the moon.",
    id: 5,
    university: "Imperial Academy of Strategy and Leadership",
    interests: ["Martial arts", "Tactical planning", "Ancient history"],
  },
  {
    images: ["https://medias.spotern.com/spots/w640/255/255774-1574993055.jpg"],
    name: "Jasmine",
    gender: "Female",
    age: 22,
    location: "4 miles away",
    bio: "Cat Mom. If you have anything about Tiger King in your bio, swiping left. Not a prize to be won.",
    id: 6,
    university: "Agrabah School of Royal Studies",
    interests: ["Skiing", "Fashion", "Animal rights activism"],
  },
];
